# Generated by Django 4.2.1 on 2023-05-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristicPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('long', models.CharField()),
                ('lat', models.CharField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('musée', 'museum'), ('plage', 'beach'), ('forrêt', 'forrest')])),
            ],
        ),
    ]
