# Generated by Django 4.2.1 on 2023-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicplace',
            name='category',
            field=models.CharField(choices=[('beach', 'beach'), ('forrest', 'forrest'), ('museum', 'museum'), ('monumant', 'monumant'), ('landmark', 'landmark'), ('public square', 'public square'), ('archaeological site', 'archaeological site'), ('garden', 'garden'), ('relegious site', 'relegious site'), ('market', 'market'), ('restaurant', 'restaurant'), ('event', 'event')], max_length=30),
        ),
        migrations.AlterField(
            model_name='touristicplace',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='touristicplace',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
