# Generated by Django 4.2.1 on 2023-06-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
