# Generated by Django 4.1.5 on 2023-05-24 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristicPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beach', 'beach'), ('museum', 'museum'), ('monument', 'monument')], max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TouristicPlaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
