# Generated by Django 4.1.5 on 2023-05-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_touristicplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='touristicplace',
            name='nb_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='multimedia')),
                ('touristicPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='multimedia')),
                ('touristicPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('touristicPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace')),
            ],
        ),
        migrations.AddField(
            model_name='touristicplace',
            name='geoinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.geoinfo'),
        ),
    ]
