# Generated by Django 4.2.1 on 2023-06-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_touristicplace_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristicplace',
            name='geoinfo',
        ),
        migrations.AddField(
            model_name='touristicplace',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristicplace',
            name='ville',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristicplace',
            name='wilaya',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
