# Generated by Django 4.2.1 on 2023-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_useraccount_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicplace',
            name='category',
            field=models.CharField(choices=[('beach', 'beach'), ('museum', 'museum'), ('monumant', 'monumant'), ('landmark', 'landmark'), ('public square', 'public square'), ('archaeological site', 'archaeological site'), ('garden', 'garden'), ('relegious site', 'relegious site'), ('market', 'market'), ('restaurant', 'restaurant')], max_length=30),
        ),
    ]
