# Generated by Django 4.1.5 on 2023-05-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_geoinfo_touristicplace_nb_visitors_video_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='touristicPlace',
            new_name='touristicplace',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='touristicPlace',
            new_name='touristicplace',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='touristicPlace',
            new_name='touristicplace',
        ),
    ]
