# Generated by Django 4.2.1 on 2023-05-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_geoinfo_touristicplace_nb_visitors_video_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='touristicPlace',
        ),
    ]
