# Generated by Django 4.2.1 on 2023-06-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_touristicplace_geoinfo_touristicplace_region_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoInfo',
        ),
    ]
