# Generated by Django 4.2.1 on 2023-06-14 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_video_touristicplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='region',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(58)]),
        ),
        migrations.AddField(
            model_name='video',
            name='touristicPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='touristicPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='touristicPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.touristicplace'),
        ),
    ]
