# Generated by Django 4.2.1 on 2023-06-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_geoinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('region', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.TextField(max_length=50)),
            ],
        ),
    ]
