# Generated by Django 4.2.1 on 2023-06-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_useraccount_region_video_touristicplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicplace',
            name='category',
            field=models.CharField(choices=[('beach', 'beach'), ('museum', 'museum'), ('monumant', 'monumant')], max_length=30),
        ),
    ]
